version: '3'
services:
  movies:
    image: maddy777/moviesrepopaytm:latest
    ports:
      - "80:80"
  train:
    image: maddy777/trainrepopaytm:latest
    ports:
      - "81:80"
  dth:
    image: maddy777/dthrepopaytm:latest
    ports:
      - "82:80"
  recharge:
    image: maddy777/rechargerepopaytm:latest
    ports:
      - "83:80"
